### ISSUE TITLE
Error cleaning up after first save

### ISSUE THREAD

**Issue by brinkdinges** [angelsix/solidworks-api#20]
I'm in the process of adding Save and Save As buttons to my application. When I save a model using for the first time (using ModelDocExtension.SaveAs), Model.cs reloads the model data and tries to destroy all previous references. This results in the exception "An attempt has been made to free an RCW that is in use" by SolidDnaObject.Dispose: Marshall.FinalReleaseComObject when mBaseObject is a modelExtensionClass.

Is this expected behavior? How can I prevent this from happening? I tried adding the save functionality to the SolidDna ModelExtension, but that gives the same error, I assume because it uses the same object.

For now I have disabled the ReloadModelData on first save and only update HasBeenSaved and FilePath That seems to work well.

**Comment by angelsix** [comment]
See if the latest code works now... seems to for me https://github.com/angelsix/solidworks-api/commit/48e72d83c97ec99d3c3888b30e3e0191e6df76c4

You can now just do ActiveModel.SaveAs as I did all the code in there for you too

**Comment by brinkdinges** [comment]
Works for me as well, thanks.
