### ISSUE TITLE
wrong Text Format on 

### ISSUE THREAD

**Issue by emersonbottero** [angelsix/solidworks-api#29]
![image](https://user-images.githubusercontent.com/12377432/39343104-87629e9c-49b1-11e8-80be-e077b9d23775.png)

should be versão 4.7

**Comment by angelsix** [comment]
This is the error message of regasm.exe when the dll cannot be successfully registered. Nothing to do with this source code

**Comment by emersonbottero** [comment]
Are you sure?In the terminal it works well. You change the text and I don't need it now, maybe when there is an error.
In other situations we set
 Encoding.GetEncoding("iso-8859-1")
or
Encoding.GetEncoding(28591)
is it possible?

![image](https://user-images.githubusercontent.com/12377432/42638881-1abe641a-85c5-11e8-86d2-26ba76e7f0af.png)

**Comment by angelsix** [comment]
The error we just fixed for detecting success when non-english version was called will of likely fixed this same issue
