### ISSUE TITLE
Missing DependencyInjection.dll or dependency

### ISSUE THREAD

**Issue by brinkdinges** [angelsix/solidworks-api#31]
Hi Luke,

We've been testing the latest version of SolidDna by making an addin from scratch and we can't get the addin to run after commit 01f1c7bc23ce34f3ba56d4d502f9ed6459e5d2eb. We started at the latest version and we tried both the NuGet package and the cloned repo as a reference.  It seems that the reference to the Dna Framework is causing an issue.

DependencyInjection.dll doesn't get copied to the output directory, but its dependency DependencyInjection.Abstractions.dll does. The exception shows no details on which assembly it's looking for.

Any idea what's going on here? 

![screenshot0](https://user-images.githubusercontent.com/15387410/39825553-526c9584-53b2-11e8-8c0f-712bbd824be9.png)

![screenshot1](https://user-images.githubusercontent.com/15387410/39825166-754a75cc-53b1-11e8-80cc-2edba157cbb5.png)

![screenshot3](https://user-images.githubusercontent.com/15387410/39825167-756c00a2-53b1-11e8-924f-45cb606939e8.png)

![screenshot2](https://user-images.githubusercontent.com/15387410/39825168-75912b8e-53b1-11e8-92a1-967cb8386079.png)

**Comment by angelsix** [comment]
Are you following this way? https://www.youtube.com/watch?v=r8e3xFlmZ_o

Also make sure you add the package restore style to the csproj file thats the key, and your framework is 4.7.1. All explained in the video. 

If you still get issues re-open ticket.
