### ISSUE TITLE
AngelSix.SolidDna nuget package

### ISSUE THREAD

**Issue by doronkind** [angelsix/solidworks-api#32]
Luke, good morning!

I want to ask you about your experience in SolidWorks add-in writing. I've found your YouTube lessons and according to them tried to implement several add-ins. Later I've found the Nuget package AngelSix.SolidDna and tried to add this, cause it incapsulate great sw API features. 

Unfortunately I run into trouble, cause

1. When I add Nuget package instead of the reference to the SolidDna project I can't download add-in, but it can be solved by adding SolidWorks.Interop.* dlls (But do we need to add them directly, if Nuget packege incapsulate features)

2. When I tried to debug add-in 've notice, that method "ConnectedToSolidWorks" has never been called. But whan I return the reference instead of the Nuget package it works.

Could you advice me the best approach according to your API and it would be great if you tell me about the Nuget package state, does it stable and can be used?

P.S. I am working with the SW 2016

**Comment by angelsix** [comment]
The main difference will be you need to edit your csproj file and add this https://github.com/angelsix/solidworks-api/blob/develop/Tutorials/07-SolidDnaNuGet/SolidDnaNuGet/SolidDnaNuGet.csproj#L14  `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>`

You can see it here https://www.youtube.com/watch?v=r8e3xFlmZ_o

Also now there is a simple template you can download and use so you can do New Project - SolidDNA to create a project for you. https://www.youtube.com/watch?v=Jhi1WFp47Qk (near last 5 minutes of video)

Let me know if you still have issues

**Comment by doronkind** [comment]
@angelsix Unfortunately it didn't help! 

I've tried to use your tutorial example with nuget in this way: 
1. Add references and set Embed interop types to false;
2. Restore Nuget package.
3. Build project and load add-in
4. Start debuging in SW
5. Add breakpoint in the "ConnectedToSolidWorks" method
6. Enable add-in

but the method ConnectedToSolidWorks still has never been called. BTW method PreConnectToSolidWorks called. 

Is the add-ins menu a see the following image: 

![image](https://user-images.githubusercontent.com/39615248/40651945-9ece705e-633f-11e8-9810-daf832af89ce.png)

Load time always "--" and it seems, that the add-in can't connect

**Comment by angelsix** [comment]
If you have created it from the project new, you don't have to add references, they already exist. So are you sure you have tested it from the new project?

**Comment by doronkind** [comment]
I did the same as in this video: https://www.youtube.com/watch?v=r8e3xFlmZ_o

**Comment by angelsix** [comment]
Ok to confirm if its your project or something else, just go to `Tools - Extensions` search for `SolidDNA` install that, then go `Project - New - SolidDNA - Blank SolidDNA project`, build and register that, run and see if that works

**Comment by doronkind** [comment]
Unfortunately, the same result, even if I use SolidDNA template. Maybe it is because of the 2016 version of the SW?

**Comment by angelsix** [comment]
Possibly a SW 2016 issue then. I'm away on holiday at moment but will install SW2016 when I can over next day or so and test. 

In the meantime can you just reference the SolidDNA source code instead and step into it line by line or turn on Ctrl + Alt + E and check the second box down then debug it and see if anything crashes. The template you created details how to debug SolidWorks and also the boot order of a SolidDNA template so you could see at what point it fails. 

If not don't worry I'll debug it myself shortly but I may not see any issue even if so. Hopefully I will see an issue on SW2016 and will fix. 

Also can you download a trial of SW2017 or 2018 to test it works on that?

**Comment by doronkind** [comment]
Sure, I am going to try with SW 2018, hope it will be succesfull! Thank you for help!

**Comment by doronkind** [comment]
@angelsix I've checked the benaviour with 2018 version and it still wrong, so, maybe this problem related with my computer. I am going to try the same on another one and after this tell you about results.

**Comment by doronkind** [comment]
@angelsix BTW could you describe how icons list path works for commands. Is it just several .png joined into one?

**Comment by angelsix** [comment]
It's it's in there and hitting preload it's not your PC. Do you have multiple SolidDNA addins installed?

**Comment by doronkind** [comment]
Maybe yes, but I'am not sure. I've tried to clean this branch in the registry:

![image](https://user-images.githubusercontent.com/39615248/40661088-86718660-635b-11e8-9de2-e3785ff3034a.png)

**Comment by angelsix** [comment]
For the icons yeah look in source it describes it https://github.com/angelsix/solidworks-api/blob/develop/SolidDna/AngelSix.SolidDna/SolidWorks/CommandManager/Group/CommandManagerGroup.cs

**Comment by angelsix** [comment]
Can you debug the startup flow. The flow is explained here. See at what point it stops loading https://github.com/angelsix/solidworks-api/blob/develop/Templates/SolidDna.Blank/SolidDNA.Blank/SolidDnaIntegration.cs

**Comment by angelsix** [comment]
Ok fresh PC, fresh install, from template. Found the issue... investigating now
![screenshot_1](https://user-images.githubusercontent.com/4455939/40710181-e68740dc-63ef-11e8-9877-39db38152503.png)

**Comment by doronkind** [comment]
Sounds good, If you need more questions ready to help

**Comment by angelsix** [comment]
Ok so should be fixed now. Underlying issue was simply an old version of Dna Framework being referenced that isn't available. I've updated SolidDna https://github.com/angelsix/solidworks-api/commit/0d2b45255cb2a226071c73ef5abb6e5aa183fe70

Then a new NuGet package is now available for SolidDna 1.0.0.9 https://www.nuget.org/packages/AngelSix.SolidDna/

Finally, I've updated the template https://github.com/angelsix/solidworks-api/tree/develop/Templates/SolidDna.Blank/SolidDNA.Blank it now has an appsettings.json file that sets the logging to trace to output everything, and then you now get full console, debug (and file https://github.com/angelsix/solidworks-api/blob/develop/Templates/SolidDna.Blank/SolidDNA.Blank/SolidDnaIntegration.cs#L99) log of the startup process so you can see it more clearly and debug any issues in future.

![screenshot_1](https://user-images.githubusercontent.com/4455939/40718685-e0c3aa6e-6408-11e8-95bf-b59b630d8610.png)

If you still get issues now after using the new SolidDNA template 1.0.1 https://marketplace.visualstudio.com/items?itemName=AngelSix.soliddna-blank or from the NuGet package, let me know. 

Also let me know if it now works.

**Comment by angelsix** [comment]
And if you add the file logging https://github.com/angelsix/solidworks-api/blob/develop/Templates/SolidDna.Blank/SolidDNA.Blank/SolidDnaIntegration.cs#L99 you will get a file log output like this too

![screenshot_1](https://user-images.githubusercontent.com/4455939/40718763-25180944-6409-11e8-8a78-e24e9237d7e0.png)

**Comment by doronkind** [comment]
@angelsix I've added SolidDna 1.0.0.9 and right now it works as expected. Thanks for the help, your SW API is really great!

**Comment by angelsix** [comment]
Cool. On a slight side-note there is a new WPF blank template in the templates now if you wanted to make use of that also https://marketplace.visualstudio.com/items?itemName=AngelSix.soliddna-blank
