### ISSUE TITLE
SolidWorks Addin Installer

### ISSUE THREAD

**Issue by emersonbottero** [angelsix/solidworks-api#41]
it says "Unexpected Response" when the computer language is not english. 
But it install the dlls.
Maybe a Localization string are needed...

**Comment by angelsix** [comment]
Can you provide me details. Screenshots at least and ideally your compiled project and dll so I can try on my machine

**Comment by emersonbottero** [comment]
I try on the Export example you provide in tutorials
![image](https://user-images.githubusercontent.com/12377432/42528042-b8e09864-8450-11e8-9dd4-9f31ea4f3bfb.png)

it Should be "Êxito" the Text values translates wrongly.

**Comment by angelsix** [comment]
Yeah the localisation right now is English. It should fallback to English I guess instead of null. I will get this fixed

**Comment by angelsix** [comment]
Fixed https://github.com/angelsix/solidworks-api/commit/f1e84aae34b1ce4a2e585ddf8a56a8c343a7320c

**Comment by emersonbottero** [comment]
Confirmed in tests. Looks Great Now.
