### ISSUE TITLE
Installation fails, says .NET standard file is missing

### ISSUE THREAD

**Issue by brinkdinges** [angelsix/solidworks-api#56]
Hi there,

My customer can't install recent versions of my add-in. The installation runs fine, but the add-in isn't registered correctly in SolidWorks. I've run regasm manually at his pc to find the culprit and this was the result: 

![screenshot3-1](https://user-images.githubusercontent.com/15387410/45943644-6fde7280-bfe7-11e8-85c9-07cd821aec19.png)
(His pc is set to Dutch, yuk. I hope you get the gist)

For this version I changed the SolidDna reference from a project to the new NuGet package. It seems something goes wrong with the reference to .NET Standard that is used by Dna.FrameWork. I found a few links that might  reference the same issue:

https://github.com/dotnet/standard/issues/481
https://github.com/Microsoft/msbuild/pull/2567
https://github.com/dotnet/standard/issues/542

While .NET 4.7.1 should support .NET Standard 2.0 completely, it seems there was an issue in MSBuild. It should be fixed in recent VS updates, but I still have this issue. Any idea how to prevent this issue?

**Comment by angelsix** [comment]
Update your project to 4.7.2 and try again. Let me know, if still and issue let me know exactly what you do to get it to fail. I have just released an add-in yesterday and it registers just fine, but I'm using 4.7.2

**Comment by brinkdinges** [comment]
Just did, same error message. 

I did find out my customer only has .NET 4.6.2 and that is the latest version that is supported for his current (and old) Windows 10 version 1511:
https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-10

What I did to exclude issues with the installer was:
- Build solution in debug mode
- Copy bin/debug folder to his pc
- Run regasm /register /codebase _PathDoDLL_

My questions:
- When we target 4.7.2, will that cause troubles for every customer that doesn't have this version installed? I've been reading about .net versions for a couple of days now, but this is not completely clear to me yet.
- Can I add support for 4.6.2? Should I add a second target framework for that to my projects?  I'm not too keen on asking my customer to update their PCs.

**Comment by angelsix** [comment]
Basically the issue has been your installer is not adding the .Net Framework as a pre-requisite for your program, which it is. So if you don't correctly ensure the prerequisites it will fail. You should either lower your .Net framework to 4.6.2 or better actually have your installer check and install the correct .Net framework
