### ISSUE TITLE
Dynamic PlugIn Reloading feature in SolidDNA template

### ISSUE THREAD

**Issue by MaxFromManaspark** [angelsix/solidworks-api#60]
Hi all,

I have tried to add the dynamic reloading functionality to my SolidWorks plugIn I have created with the help of the SolidDNA templates.

So in my PlugIn_Integration, which derives from AddInIntegration, I have added this line of code:

`public override void PreConnectToSolidWorks()
        {
            // NOTE: To run in our own AppDomain do the following
            //       Be aware doing so sometimes causes API's to fail
            //       when they try to load dll's
            PlugInIntegration.UseDetachedAppDomain = true;
        }
`

The magic line here is `PlugInIntegration.UseDetachedAppDomain = true;`

But unfortunately I get the following errors which are thrown in the SolidDNA Setup() method:

"SLDWORKS.exe" (CLR v4.0.30319: DefaultDomain): "Anonymously Hosted DynamicMethods Assembly" geladen. 
Dna: Debug: Firing PreConnectToSolidWorks... [AddinIntegration.cs > ConnectToSW() > Line 151]
Dna: Debug: Setting AddinCallbackInfo... [AddinIntegration.cs > ConnectToSW() > Line 165]
Dna: Debug: PlugInIntegration Setup... [AddinIntegration.cs > ConnectToSW() > Line 171]
Dna: Debug: Detached AppDomain PlugIn Setup... [PlugInIntegration.cs > Setup() > Line 88]
"SLDWORKS.exe" (CLR v4.0.30319: Domain 2): "C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"SLDWORKS.exe" (CLR v4.0.30319: SolidDnaPlugInDomain): "D:\VIP\AssemblyExporter_MasterThesis\02_Solidworks_Addin\PolyG_Exporter\SW.PolyG_Exporter\PolyG_Exporter for SolidWorks\bin\Debug\AngelSix.SolidDna.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"SLDWORKS.exe" (CLR v4.0.30319: SolidDnaPlugInDomain): "D:\VIP\AssemblyExporter_MasterThesis\02_Solidworks_Addin\PolyG_Exporter\SW.PolyG_Exporter\PolyG_Exporter for SolidWorks\bin\Debug\Microsoft.Extensions.Logging.Abstractions.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"SLDWORKS.exe" (CLR v4.0.30319: SolidDnaPlugInDomain): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll" geladen. Das Modul wurde ohne Symbole erstellt.
"SLDWORKS.exe" (CLR v4.0.30319: SolidDnaPlugInDomain): "D:\VIP\AssemblyExporter_MasterThesis\02_Solidworks_Addin\PolyG_Exporter\SW.PolyG_Exporter\PolyG_Exporter for SolidWorks\bin\Debug\Dna.Framework.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
"SLDWORKS.exe" (CLR v4.0.30319: SolidDnaPlugInDomain): "D:\VIP\AssemblyExporter_MasterThesis\02_Solidworks_Addin\PolyG_Exporter\SW.PolyG_Exporter\PolyG_Exporter for SolidWorks\bin\Debug\SolidWorks.Interop.sldworks.dll" geladen. Das Modul wurde ohne Symbole erstellt.
"SLDWORKS.exe" (CLR v4.0.30319: SolidDnaPlugInDomain): "D:\VIP\AssemblyExporter_MasterThesis\02_Solidworks_Addin\PolyG_Exporter\SW.PolyG_Exporter\PolyG_Exporter for SolidWorks\bin\Debug\SolidWorks.Interop.swpublished.dll" geladen. Das Modul wurde ohne Symbole erstellt.
"SLDWORKS.exe" (CLR v4.0.30319: SolidDnaPlugInDomain): "D:\VIP\AssemblyExporter_MasterThesis\02_Solidworks_Addin\PolyG_Exporter\SW.PolyG_Exporter\PolyG_Exporter for SolidWorks\bin\Debug\Microsoft.Extensions.DependencyInjection.Abstractions.dll" geladen. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
Ausnahme ausgelöst: "System.NullReferenceException" in AngelSix.SolidDna.dll
Ausnahme ausgelöst: "System.NullReferenceException" in AngelSix.SolidDna.dll
Dna: Critical: Unexpected error: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei AngelSix.SolidDna.PlugInIntegration.Setup(String addinPath, String version, Int32 cookie)
   bei AngelSix.SolidDna.PlugInIntegrationMarshal.SetupAppDomain(String addinPath, String version, Int32 cookie)
   bei AngelSix.SolidDna.PlugInIntegrationMarshal.SetupAppDomain(String addinPath, String version, Int32 cookie)
   bei AngelSix.SolidDna.PlugInIntegration.Setup(String addinPath, String version, Int32 cookie)
   bei AngelSix.SolidDna.AddInIntegration.ConnectToSW(Object ThisSW, Int32 Cookie) [AddinIntegration.cs > ConnectToSW() > Line 214]

I have tracked the issue down to this section in the SolidDNA .dll:

`
public static void Setup(string addinPath, string version, int cookie)
        {
            if (UseDetachedAppDomain)
            {
                // Log it
                Logger.LogDebugSource($"Detached AppDomain PlugIn Setup...");

                // Make sure we resolve assemblies in this domain, as it seems to use this domain to resolve
                // assemblies not the appDomain when crossing boundaries
                AppDomain.CurrentDomain.AssemblyResolve += PlugInIntegrationMarshal.AppDomain_AssemblyResolve;

                PlugInAppDomain = AppDomain.CreateDomain("SolidDnaPlugInDomain", null, new AppDomainSetup
                {
                    // Use plug-in folder for resolving plug-ins
                    ApplicationBase = addinPath,
                });

                // Make sure we load our own marshal
                AssembliesToResolve.Add(typeof(PlugInIntegrationMarshal).Assembly.FullName);

                // Run code on new app-domain to configure
                PluginCrossDomain = (PlugInIntegrationMarshal)PlugInAppDomain.CreateInstanceAndUnwrap(typeof(PlugInIntegrationMarshal).Assembly.FullName, typeof(PlugInIntegrationMarshal).FullName);

                // Setup
                PluginCrossDomain.SetupAppDomain(addinPath, version, cookie);
            }
            else
            {`

Maybe someone knows a quick fix or workaround to get the dynamic reloading feature working.

Cheers,
Max.

**Comment by painezeng** [comment]
yes, i also have this problem. 
Exception thrown: 'System.NullReferenceException' in Dna.Framework.dll
Exception thrown: 'System.NullReferenceException' in AngelSix.SolidDna.dll
Dna: Critical: Unexpected error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Dna.FrameworkDI.get_Logger()
   at AngelSix.SolidDna.PlugInIntegration.Setup(String addinPath, String version, Int32 cookie)
   at AngelSix.SolidDna.PlugInIntegrationMarshal.SetupAppDomain(String addinPath, String version, Int32 cookie)
   at AngelSix.SolidDna.PlugInIntegrationMarshal.SetupAppDomain(String addinPath, String version, Int32 cookie)
   at AngelSix.SolidDna.PlugInIntegration.Setup(String addinPath, String version, Int32 cookie)
   at AngelSix.SolidDna.AddInIntegration.ConnectToSW(Object ThisSW, Int32 Cookie) [AddinIntegration.cs > ConnectToSW() > Line 214]

**Comment by Flydoo** [comment]
Hi,

I also wanted to make use of the dynamic reload functionality. But setting PlugInIntegration.UseDetachedAppDomain to true gives me this error:

Dna: Critical: Unexpected error: System.InvalidCastException: Unable to cast transparent proxy to type 'AngelSix.SolidDna.PlugInIntegrationMarshal'.
   at AngelSix.SolidDna.PlugInIntegration.Setup(String addinPath, String version, Int32 cookie)
   at AngelSix.SolidDna.AddInIntegration.ConnectToSW(Object thisSw, Int32 cookie) [AddInIntegration.cs > ConnectToSW() > Line 258]

I'm using VS 2019 and SolidWorks 2017.
Any Idea how to solve this?

BR
Lars

**Comment by angelsix** [comment]
Fixed https://github.com/angelsix/solidworks-api/commit/79aa351ddf17ab5ce4c2c51c1c37daaaf806f001 and https://github.com/angelsix/solidworks-api/commit/94e307509dca834fd34a6b63905ab415abdb37da

Basically now all you need to do is set AppDomainBoundary.UseDetachedAppDomain = true; in PreConnectToSolidWorks. You can use the sample tutorial project thats up to date and working.

Remember to regasm both the dlls (addin and plugin dll project)
