### ISSUE TITLE
Model.SelectionChanged event doesn't trigger on all selection changes

### ISSUE THREAD

**Issue by SamoilovVV** [angelsix/solidworks-api#62]
Hi!
I'm working with assemblies in SolidWorks 2018 and experienced some problems with Model.SelectionChanged event:
1)"Invert Selection" fires SelectionChanged event only for deselecting currently selected objects.
Newly selected objects (Invert Selection result) doesn't trigger this event.
2) Changing selection in Selection Breadcrumbs also doesn't trigger this event.

Subscribing to DAssemblyDocEvents_NewSelectionNotifyEventHandler solves this issue, but SolidDNA API is great and I prefer to use it in most cases.

**Comment by angelsix** [comment]
Can you provide a bit more detail (an assembly to test, manual steps to "see" this issue) and I'll make a fix for it in SolidDNA over christmas :)
