### ISSUE TITLE
How to get current active SldWorks instance back from SolidWorksApplication

### ISSUE THREAD

**Issue by Venzentzheng** [angelsix/solidworks-api#63]
I need active SldWork instance to interact with other Solidworks Add-ons, have tried **(SldWorks)Marshal.GetActiveObject("SldWorks.Application")** but no luck with it, any suggestions please ?

**Comment by alexanderklammer** [comment]
Hi, i think you will find what you need here: 
https://forum.solidworks.com/thread/215594

Br Alex
