### ISSUE TITLE
Custom Properties Tutorial Crash in AddToTaskpaneAsync()

### ISSUE THREAD

**Issue by SolidworksDev** [angelsix/solidworks-api#64]
I'm using the master branch.  Running Solidworks 2018 on a Windows 7 box.  When I run the tutorial 03-CustomProperties in the debugger it throws the exception "System.InvalidOperationException: 'The calling thread must be STA, because many UI components require this.'" on line 92 of TaskpaneIntegration.cs.  I have another project that I am using the Nuget release v1.0.1.8 and I'm am able to instantiate the Taskpane without throwing an exception.  I'm building both projects with .NETFramework Version v4.7.2.  This exception is thrown in both the master and developer branches of tutorial 03-CustomProperties.  This appears to be a problem with the tutorial because if I replace the NuGet package with the source code for SolidDna my project does not throw the exception.  I found this issue because I wanted to overload the function AddToTaskpaneAsync to pass in a string to set the title of the pane to something other than the name of the addin.  I was successful with overloading the function in my project.   Is there currently some other way to change the title of the Taskpane?

**Comment by angelsix** [comment]
Change line 85 of SolidDnaIntegration to `mTaskpane.AddToTaskpaneAsync();`. I've fixed the example code. Good cathc
