### ISSUE TITLE
Error Preventing Repository Examples From Running  

### ISSUE THREAD

**Issue by mgmagliola** [angelsix/solidworks-api#65]
Hello All,

I'll preface this with I am new to programming in general, I apologize if this is not the place for this sort of post and if so would appreciate a recommendation for where such posts are accepted. 

Before now I had followed tutorials 1 - 3 for the SolidWorks Add-in Programming and was able to get add-ins working for 1 and 2. I have attached my code that works (for me) for reference.  I was hoping to look through the completed tutorials from the repository to help me with debugging my own code from the 3rd tutorial however when I run the code from the repository I get a popup window saying that:

"A project with an output type of class library cannot be started directly. in order to debug this project, add an executable project to this solution which references the library project. set the executable project as the startup project."

![2019 05 02_API_Debug_Issue_3](https://user-images.githubusercontent.com/50223214/57117066-6b213000-6d27-11e9-8ce6-5236dc2ab888.png)

I tried to troubleshoot on my and understand that with multi-project programs you have to specify the startup project. In this instance there are the 2 projects, the SolidDna.CustomProperties and the Solid.Dna and so checked to make sure the right project file was selected as the startup file, by default the SolidDna.CustomProperties Project was selected. 

![2019 05 02_API_Debug_Issue_4](https://user-images.githubusercontent.com/50223214/57117104-aa4f8100-6d27-11e9-88ef-a589278b2528.png)

More specifically I was trying to run the program contained in the SolidDna.CustomProperties folder from the repository. I would add my functioning code and the code I can't get to work but I can't find a way to attach a folder so if anyone wants the files I can email them or maybe there is a better way?

Any help with this issue would be greatly appreciated.

**Comment by angelsix** [comment]
If you read the newer tutorials or videos it tells you what to do

https://github.com/angelsix/solidworks-api/blob/develop/Tutorials/07-SolidDnaNuGet/SolidDnaNuGet/SolidDnaIntegration.cs
