### ISSUE TITLE
Expression is always true/false

### ISSUE THREAD

**Issue by brinkdinges** [angelsix/solidworks-api#71]
Resharper shows a few "Expression always true/false" warnings, but I can't judge them properly myself. I'll let you judge them. They are:

SolidWorksApplication line 257 (always true)
`activeDoc != null`

SolidWorksApplication line 483 (always false)
`if (xmlDoc == null)`

PluginIntegration, line 342 (always true)
`if (plugin != null)`

PluginIntegration, line 393 (always false)
`if (assembly == null)`

**Comment by angelsix** [comment]
Confirmed, first one is correct. XmlDocument appears correct too based on this https://referencesource.microsoft.com/#System.Xml.Linq/System/Xml/Linq/XLinq.cs,4029.

plugin != null is invalid, it can be null https://referencesource.microsoft.com/#mscorlib/system/appdomain.cs,4519

For assembly == null I cannot confirm. The rabbit hole ends here https://referencesource.microsoft.com/#mscorlib/system/reflection/assembly.cs,1911 but I would leave it in as it likely can return null.

Feel free to fix the first two
