### ISSUE TITLE
Supporting Visual Studio 2019 ? 

### ISSUE THREAD

**Issue by Venzentzheng** [angelsix/solidworks-api#80]
I am aware of that I can not find any SolidDNA templates in Visual Studio 2019, just checking.

**Comment by Venzentzheng** [comment]
The another reason I am asking is when I debug my SolidDNA project, it is throwing InvalidCastException from both baseObject and UnsafeObject. just let you know.

**Comment by angelsix** [comment]
The templates are available on 2019. Just go to Extensions then Online and search SolidDNA. 

You can also pull source and reference the SolidDNA solution and debug that way.
