### ISSUE TITLE
assemblyBinding not beeing read in plugin

### ISSUE THREAD

**Issue by oscilate** [angelsix/solidworks-api#83]
Hi All,

I need a plugin developed using the api to support binding redirects that are present in the addin.dll.config file. 

However at runtime, this file ins't read and I get FileNotFoundException trying to load assemblies at a lower version than the ones i have available.

Is there a way to make the plugin pick up this file?

Thanks

**Comment by angelsix** [comment]
As SolidWorks loads the dll it won't honour that file at a guess and thats the issue. You can add your own assembly resolver like here https://github.com/angelsix/solidworks-api/blob/45a9bd82924f38bd64359b030832d4280b5d7147/SolidDna/AngelSix.SolidDna/SolidWorks/Integration/AddIn/AddInIntegration.cs#L90
