### ISSUE TITLE
Error when manually load AddIn

### ISSUE THREAD

**Issue by lexius** [angelsix/solidworks-api#90]
Hello. I have an exception when try to load AddIn manually from Solidworks addins window.

> 
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
Dna: Critical: Unexpected error: System.InvalidOperationException: La raccolta è stata modificata. L'operazione di enumerazione potrebbe non essere eseguita.
   in System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   in System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   in AngelSix.SolidDna.PlugInIntegration.SolidDnaPlugIns(String addinPath)
   in AngelSix.SolidDna.PlugInIntegration.ConfigurePlugIns(String addinPath)
   in AngelSix.SolidDna.AddInIntegration.ConnectToSW(Object thisSw, Int32 cookie) [AddInIntegration.cs > ConnectToSW() > Line 258]
>

**Comment by angelsix** [comment]
Fixed https://github.com/angelsix/solidworks-api/commit/3fa472d04adc664912ffb0fd17f0c47577202f19
